#
# HandGiveAll Config
# Made By horyu1234
#
# Copyright 2014 ~ 2017 . HoryuSystems Ltd . All rights reserved
#
config: 1.6
# If you agree with the end user license agreement, set eula to true
# You can only use this plugin if you agree with the eula
#
# EULA: https://horyu1234.com/EULA
#
# EULA: false  If you agree with the end user license agreement, set this to true
# use_english: true to use english, set this to true
#
# show_console_msg: false if you want to view plugin messages through in-game chat, set this to true
# show_inv_full_msg: true if there’s someone with a full inventory and didn’t receive the item, a message is shown
# show_message_box: false pops open a visual message
# use_nickname: false use player’s nickname instead of actual username.
# use_item_display_name: true if there’s a custom display name set for an item, use that instead for messages.
# use_firework: true when an item or money is given to everyone, add fireworks.
# money_unit: "Dollar" Use the currency unit of the server. If you don’t have a currency system in your server, ignore this option.
# max_point_count: 3 set the amount of decimals to show for money. Min: 1(If you don’t have a currency system in your server, ignore this option.)
#
# ▼▼▼ Below contains actual configuration. ▼▼▼

EULA: false
use_english: true

show_console_msg: false
show_inv_full_msg: true
show_message_box: false
use_nickname: false
use_item_display_name: true
use_firework: true
money_unit: "Dollar"
max_point_count: 3